"""Golden composite-profile baselines for the canonical fixture seeds 1001-1005.

risk-engine.md §10.3 (frozen): "Golden files: one composite profile per canonical fixture
company (seeds 1001-1005), regenerated only with explicit review".
testing.md §4 (frozen): "Golden files are committed JSON (``backend/tests/golden/*.json``),
regenerated only by ``pytest --regen-golden`` ... A golden change without a
registry/twin version bump is a defect."

Regenerate with::

    pytest backend/tests/golden --regen-golden

then review the JSON diff and note it in the development log.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from backend.data_engine.contracts import SyntheticCompanyConfig
from backend.data_engine.ingest.synthetic import generate_company
from backend.risk_engine.contracts import REGISTRY_VERSION
from backend.risk_engine.engine import QuantitativeRiskEngine

GOLDEN_DIR = Path(__file__).resolve().parent
CANONICAL_SEEDS = (1001, 1002, 1003, 1004, 1005)
TOLERANCE = 1e-9


def _golden_path(seed: int) -> Path:
    return GOLDEN_DIR / f"seed_{seed}.json"


def _profile(seed: int) -> dict[str, Any]:
    """Deterministic composite risk profile for one canonical fixture seed."""
    dataset = generate_company(SyntheticCompanyConfig(seed=seed, periods=24))
    report = QuantitativeRiskEngine().evaluate_company(dataset)
    composite = report.composite
    sensitivity = report.sensitivity

    return {
        "seed": seed,
        "registry_version": report.registry_version,
        "composite_score": composite.score,
        "composite_severity": composite.severity.value if composite.severity is not None else None,
        "total_contributions": composite.total_contributions,
        "missing_dimensions": list(composite.missing_dimensions),
        "dimensions": {
            dim_id: {
                "score": dimension.score,
                "severity": (dimension.severity.value if dimension.severity is not None else None),
                "weight": dimension.weight,
                "effective_weight": dimension.effective_weight,
                "contribution": dimension.contribution,
            }
            for dim_id, dimension in composite.dimensions.items()
        },
        "sensitivity": {
            "baseline_score": sensitivity.baseline_score,
            "min_score": sensitivity.min_score,
            "max_score": sensitivity.max_score,
            "score_range": sensitivity.score_range,
            "rank_stability_score": sensitivity.rank_stability_score,
        },
    }


def _compare(expected: Any, actual: Any, path: str) -> None:
    """Recursively compare a golden document with a live one, floats within tolerance."""
    if expected is None or actual is None:
        assert expected is None and actual is None, f"{path}: {actual!r} != {expected!r}"
        return
    if isinstance(expected, dict):
        assert isinstance(actual, dict), f"{path}: expected a mapping"
        assert set(expected) == set(actual), (
            f"{path}: keys differ ({sorted(set(expected) ^ set(actual))})"
        )
        for key in sorted(expected):
            _compare(expected[key], actual[key], f"{path}.{key}")
        return
    if isinstance(expected, list):
        assert isinstance(actual, list) and len(expected) == len(actual), f"{path}: length differs"
        for index, (exp_item, act_item) in enumerate(zip(expected, actual, strict=True)):
            _compare(exp_item, act_item, f"{path}[{index}]")
        return
    if isinstance(expected, bool) or isinstance(expected, str):
        assert expected == actual, f"{path}: {actual!r} != {expected!r}"
        return
    if isinstance(expected, int | float):
        assert actual == pytest.approx(expected, abs=TOLERANCE), (
            f"{path}: {actual!r} != {expected!r}"
        )
        return
    assert expected == actual, f"{path}: {actual!r} != {expected!r}"


def test_golden_baselines_exist_for_all_canonical_seeds(regen_golden: bool) -> None:
    if regen_golden:
        pytest.skip("baselines are being regenerated by this run")
    missing = [seed for seed in CANONICAL_SEEDS if not _golden_path(seed).exists()]
    assert not missing, f"missing golden baselines for seeds {missing}; run --regen-golden"


@pytest.mark.parametrize("seed", CANONICAL_SEEDS)
def test_golden_composite_profile(seed: int, regen_golden: bool) -> None:
    actual = _profile(seed)
    path = _golden_path(seed)

    if regen_golden:
        path.write_text(json.dumps(actual, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        return

    assert path.exists(), f"missing {path.name}; regenerate with --regen-golden"
    golden = json.loads(path.read_text(encoding="utf-8"))

    # A golden change without a registry version bump is a defect (testing.md §4).
    assert golden["registry_version"] == REGISTRY_VERSION, (
        f"{path.name} was generated by registry {golden['registry_version']} but the "
        f"code now reports {REGISTRY_VERSION}: regenerate and review the diff"
    )
    _compare(golden, actual, path.name)


@pytest.mark.parametrize("seed", CANONICAL_SEEDS)
def test_golden_profile_is_reproducible(seed: int) -> None:
    """Same seed + same config => identical profile (R6 determinism)."""
    assert _profile(seed) == _profile(seed)
