"""Golden baseline twin trajectories for the canonical fixture seeds 1001-1005.

simulation.md §6.6 (frozen): "Golden files: baseline trajectories for fixture
seeds 1001-1005 (testing.md)". testing.md §4 (frozen): golden files are
committed JSON, "regenerated only by ``pytest --regen-golden`` ... A golden
change without a registry/twin version bump is a defect".

These are *new* files (``twin_seed_*.json``). The existing ``seed_1001.json``..
``seed_1005.json`` are Phase 4 composite risk-profile baselines and are never
read, written or regenerated by this module.

Regenerate with::

    pytest backend/tests/golden --regen-golden

then review the JSON diff and note it in the development log, together with the
``TWIN_VERSION`` bump that a genuine trajectory change requires.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from backend.data_engine.contracts import SyntheticCompanyConfig
from backend.data_engine.ingest.synthetic import generate_company
from backend.simulation.contracts import TWIN_VERSION
from backend.simulation.twin import simulate

GOLDEN_DIR = Path(__file__).resolve().parent
CANONICAL_SEEDS = (1001, 1002, 1003, 1004, 1005)
TOLERANCE = 1e-9
HORIZON = 12

# Series compared per month: the trajectories simulation.md §5 lists as the
# twin's own outputs. KPI comparison and the EBITDA waterfall are Phase 8.
TRAJECTORY_FIELDS = (
    "revenue",
    "cogs",
    "gross_profit",
    "opex",
    "ebitda",
    "ebit",
    "interest_expense",
    "ebt",
    "tax",
    "net_income",
    "receivables",
    "inventory",
    "payables",
    "nwc",
    "ocf",
    "capex",
    "principal",
    "draws",
    "cash",
    "total_debt",
)


def _golden_path(seed: int) -> Path:
    return GOLDEN_DIR / f"twin_seed_{seed}.json"


def _trajectory(seed: int) -> dict[str, Any]:
    """Regenerate the deterministic baseline trajectory for one seed."""
    dataset = generate_company(SyntheticCompanyConfig(seed=seed, periods=24))
    result = simulate(dataset, horizon_months=HORIZON)
    return {
        "seed": seed,
        "twin_version": TWIN_VERSION,
        "horizon_months": HORIZON,
        "start_period_end": result.start_period_end.isoformat(),
        "end_period_end": result.end_period_end.isoformat(),
        "assumptions": {
            record.parameter: record.value for record in result.diagnostics.assumption_records
        },
        "trajectory": {
            field: [getattr(m, field) for m in result.months] for field in TRAJECTORY_FIELDS
        },
        "ratios": {
            "dscr": [m.dscr.value for m in result.months],
            "interest_coverage": [m.interest_coverage.value for m in result.months],
            "cash_runway_months": [m.cash_runway_months.value for m in result.months],
        },
        "summary": result.summary.model_dump(mode="json"),
    }


def _compare(expected: Any, actual: Any, path: str) -> None:
    """Recursively compare a golden document with a live one, floats within tolerance."""
    if expected is None or actual is None:
        assert expected is None and actual is None, f"{path}: {actual!r} != {expected!r}"
        return
    if isinstance(expected, dict):
        assert isinstance(actual, dict), f"{path}: expected a mapping"
        assert set(expected) == set(actual), (
            f"{path}: keys differ ({sorted(set(expected) ^ set(actual))})"
        )
        for key in sorted(expected):
            _compare(expected[key], actual[key], f"{path}.{key}")
        return
    if isinstance(expected, list):
        assert isinstance(actual, list) and len(expected) == len(actual), f"{path}: length differs"
        for index, (exp_item, act_item) in enumerate(zip(expected, actual, strict=True)):
            _compare(exp_item, act_item, f"{path}[{index}]")
        return
    if isinstance(expected, bool | str):
        assert expected == actual, f"{path}: {actual!r} != {expected!r}"
        return
    assert actual == pytest.approx(expected, abs=TOLERANCE), f"{path}: {actual!r} != {expected!r}"


def test_twin_goldens_exist_for_all_canonical_seeds(regen_golden: bool) -> None:
    if regen_golden:
        pytest.skip("baselines are being regenerated by this run")
    missing = [seed for seed in CANONICAL_SEEDS if not _golden_path(seed).exists()]
    assert not missing, f"missing twin goldens for seeds {missing}; run --regen-golden"


@pytest.mark.parametrize("seed", CANONICAL_SEEDS)
def test_golden_twin_trajectory(seed: int, regen_golden: bool) -> None:
    actual = _trajectory(seed)
    path = _golden_path(seed)

    if regen_golden:
        path.write_text(json.dumps(actual, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        return

    assert path.exists(), f"missing {path.name}; regenerate with --regen-golden"
    golden = json.loads(path.read_text(encoding="utf-8"))

    # A golden change without a twin version bump is a defect (testing.md §4).
    assert golden["twin_version"] == TWIN_VERSION, (
        f"{path.name} was generated by twin {golden['twin_version']} but the code now "
        f"reports {TWIN_VERSION}: regenerate and review the diff"
    )
    _compare(golden, actual, path.name)


@pytest.mark.parametrize("seed", CANONICAL_SEEDS)
def test_golden_twin_trajectory_is_reproducible(seed: int) -> None:
    """Same seed + same assumptions => identical trajectory (R6 determinism)."""
    assert _trajectory(seed) == _trajectory(seed)


@pytest.mark.parametrize("seed", CANONICAL_SEEDS)
def test_golden_records_the_full_horizon(seed: int) -> None:
    golden = json.loads(_golden_path(seed).read_text(encoding="utf-8"))
    assert golden["horizon_months"] == HORIZON
    for field, values in golden["trajectory"].items():
        assert len(values) == HORIZON, f"{field} is not a full horizon"
    assert golden["start_period_end"] < golden["end_period_end"]


@pytest.mark.parametrize("seed", CANONICAL_SEEDS)
def test_golden_is_separate_from_the_phase_four_profile(seed: int) -> None:
    """The Phase 4 composite-profile goldens are a separate, untouched artifact."""
    phase4 = GOLDEN_DIR / f"seed_{seed}.json"
    assert phase4.exists()
    assert _golden_path(seed) != phase4
    assert "composite_score" in json.loads(phase4.read_text(encoding="utf-8"))
    assert "trajectory" in json.loads(_golden_path(seed).read_text(encoding="utf-8"))
